/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import app.Main;


public class MPTD extends javax.swing.JFrame {
    Main main;
    public MPTD(Main main) {
        initComponents();
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        progralineal = new javax.swing.JLabel();
        mtransporte = new javax.swing.JLabel();
        lbASYSC = new javax.swing.JLabel();
        bgLogo = new javax.swing.JLabel();
        lblTema2 = new javax.swing.JLabel();
        lblTema1 = new javax.swing.JLabel();
        lblTema3 = new javax.swing.JLabel();
        lineaespera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        planactividades = new javax.swing.JLabel();
        lblTema4 = new javax.swing.JLabel();
        inventario = new javax.swing.JLabel();
        lblTema5 = new javax.swing.JLabel();
        lblFoot = new javax.swing.JLabel();
        lblFoot2 = new javax.swing.JLabel();
        lblFoot1 = new javax.swing.JLabel();
        lblFoot3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progralineal.setBackground(new java.awt.Color(255, 255, 255));
        progralineal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/progralineal.jpg"))); // NOI18N
        progralineal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        progralineal.setOpaque(true);
        progralineal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progralinealMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progralinealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progralinealMouseExited(evt);
            }
        });
        bg.add(progralineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 150, 90));

        mtransporte.setBackground(new java.awt.Color(255, 255, 255));
        mtransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mtrasnporte.png"))); // NOI18N
        mtransporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mtransporte.setOpaque(true);
        mtransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mtransporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mtransporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mtransporteMouseExited(evt);
            }
        });
        bg.add(mtransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 150, 90));

        lbASYSC.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lbASYSC.setForeground(new java.awt.Color(255, 71, 0));
        lbASYSC.setText("Portafolio Digital 2023 ITESS-TICS MPTD");
        lbASYSC.setToolTipText("");
        bg.add(lbASYSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 510, 40));

        bgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoprincipal.png"))); // NOI18N
        bg.add(bgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        lblTema2.setForeground(new java.awt.Color(255, 255, 255));
        lblTema2.setText("Unidad 2. Metodo de transporte");
        bg.add(lblTema2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        lblTema1.setForeground(new java.awt.Color(255, 255, 255));
        lblTema1.setText(" Unidad 1 Programacion Lineal");
        bg.add(lblTema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 180, -1));

        lblTema3.setForeground(new java.awt.Color(255, 255, 255));
        lblTema3.setText("Unidad 5. Lineas de espera");
        bg.add(lblTema3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        lineaespera.setBackground(new java.awt.Color(255, 255, 255));
        lineaespera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lineaespera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lineadeespera.png"))); // NOI18N
        lineaespera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lineaespera.setOpaque(true);
        lineaespera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineaesperaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lineaesperaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lineaesperaMouseExited(evt);
            }
        });
        bg.add(lineaespera, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 150, 90));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Juan Manuel Rosales Contreras y Brisa Berenice Raya Sanchez");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 470, -1));

        planactividades.setBackground(new java.awt.Color(255, 255, 255));
        planactividades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        planactividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planeaciondeact.png"))); // NOI18N
        planactividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        planactividades.setOpaque(true);
        planactividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planactividadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                planactividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                planactividadesMouseExited(evt);
            }
        });
        bg.add(planactividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 150, 90));

        lblTema4.setForeground(new java.awt.Color(255, 255, 255));
        lblTema4.setText("Unidad 3. Planeacion de actividades");
        bg.add(lblTema4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        inventario.setBackground(new java.awt.Color(255, 255, 255));
        inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventarios.png"))); // NOI18N
        inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventario.setOpaque(true);
        inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventarioMouseExited(evt);
            }
        });
        bg.add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 150, 90));

        lblTema5.setForeground(new java.awt.Color(255, 255, 255));
        lblTema5.setText("Unidad 4. Teoria de invetarios");
        bg.add(lblTema5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        lblFoot.setForeground(new java.awt.Color(255, 51, 0));
        lblFoot.setText("Brisa Berenice Raya Sanchez");
        bg.add(lblFoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        lblFoot2.setForeground(new java.awt.Color(255, 51, 0));
        lblFoot2.setText("Juan Manuel Rosales Contreras");
        bg.add(lblFoot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        lblFoot1.setForeground(new java.awt.Color(255, 51, 0));
        lblFoot1.setText("Proyecto: JMB");
        bg.add(lblFoot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        lblFoot3.setForeground(new java.awt.Color(255, 51, 0));
        lblFoot3.setText("ITESS-TICS-2023 AGO-DIC");
        bg.add(lblFoot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 819, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void progralinealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progralinealMouseEntered
        progralineal.setBackground(Color.yellow);
    }//GEN-LAST:event_progralinealMouseEntered

    private void progralinealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progralinealMouseExited
        progralineal.setBackground(Color.white);
    }//GEN-LAST:event_progralinealMouseExited

    private void mtransporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtransporteMouseEntered
        mtransporte.setBackground(Color.yellow);
    }//GEN-LAST:event_mtransporteMouseEntered

    private void mtransporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtransporteMouseExited
        mtransporte.setBackground(Color.white);
    }//GEN-LAST:event_mtransporteMouseExited

    private void progralinealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progralinealMouseClicked
        // TODO add your handling code here:
        main.mainASYS.setVisible(false);
        
        main.introduction = new ProgramacionLineal(this.main);
        main.introduction.setVisible(true);        
    }//GEN-LAST:event_progralinealMouseClicked

    private void lineaesperaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineaesperaMouseEntered
        // TODO add your handling code here:
        lineaespera.setBackground(Color.yellow);
    }//GEN-LAST:event_lineaesperaMouseEntered

    private void lineaesperaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineaesperaMouseExited
        // TODO add your handling code here:
        lineaespera.setBackground(Color.white);
    }//GEN-LAST:event_lineaesperaMouseExited

    private void mtransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtransporteMouseClicked
        // TODO add your handling code here:
        main.mainASYS.setVisible(false);
        
        main.fourierSeries = new MetodTransporte(this.main);
        main.fourierSeries.setVisible(true); 
    }//GEN-LAST:event_mtransporteMouseClicked

    private void lineaesperaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineaesperaMouseClicked
        // TODO add your handling code here:
        main.mainASYS.setVisible(false);
        
        main.fourierTransform = new LineasdeEspera(this.main);
        main.fourierTransform.setVisible(true);
    }//GEN-LAST:event_lineaesperaMouseClicked

    private void planactividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planactividadesMouseClicked
        main.mainASYS.setVisible(false);
        
        main.discreteSystem = new Planeaciondeact(this.main);
        main.discreteSystem.setVisible(true);
    }//GEN-LAST:event_planactividadesMouseClicked

    private void planactividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planactividadesMouseEntered
        planactividades.setBackground(Color.yellow);
    }//GEN-LAST:event_planactividadesMouseEntered

    private void planactividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planactividadesMouseExited
        planactividades.setBackground(Color.white);
    }//GEN-LAST:event_planactividadesMouseExited

    private void inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMouseClicked
        main.mainASYS.setVisible(false);
        
        main.tema = new Teoriadeinventarios(this.main);
        main.tema.setVisible(true);
    }//GEN-LAST:event_inventarioMouseClicked

    private void inventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMouseEntered
        inventario.setBackground(Color.yellow);
    }//GEN-LAST:event_inventarioMouseEntered

    private void inventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMouseExited
        inventario.setBackground(Color.white);
    }//GEN-LAST:event_inventarioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MPTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MPTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MPTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MPTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MPTD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgLogo;
    private javax.swing.JLabel inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbASYSC;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblFoot1;
    private javax.swing.JLabel lblFoot2;
    private javax.swing.JLabel lblFoot3;
    private javax.swing.JLabel lblTema1;
    private javax.swing.JLabel lblTema2;
    private javax.swing.JLabel lblTema3;
    private javax.swing.JLabel lblTema4;
    private javax.swing.JLabel lblTema5;
    private javax.swing.JLabel lineaespera;
    private javax.swing.JLabel mtransporte;
    private javax.swing.JLabel planactividades;
    private javax.swing.JLabel progralineal;
    // End of variables declaration//GEN-END:variables
}
